### ISSUE TITLE
Commutator calculation

### ISSUE THREAD

**Issue by vp1981** [Baradun/lomov#2]
https://github.com/Baradun/lomov/blob/09c7873859aed891fd6e209485080f75e167c78d/first-ng.py#L123

(facepalm)

Хорошо, есть коммутатор **элементов группы** и коммутатор **матриц**. Первое — вычисляется как раз так:
```
[A,B]=ABA^{-1}B^{-1}
```
но для матриц — это
```
[A,B] = AB - BA
```

Они связаны между собой, если обратиться к группам и алгебрам Ли (алгебра Ли — группа Ли в малом).

**Comment by Baradun** [comment]
Поправил
